site_name: Learn Linux
site_url: https://moabukar.github.io/unux-learn/
site_author: Mohamed Abukar
repo_url: https://github.com/moabukar/unix-learn
dev_addr: "127.0.0.1:8000"
docs_dir: docs
theme: 
  name: material
  # custom_dir: overrides
  extra_css:
    - stylesheets/custom.css

  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: dark_blue
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

nav:
- Home: home_page.md
- Linux:
    - Command-line:
        - Alias: command-line/alias-command.md
        - Cat: command-line/cat-command.md
        - Change Directory: command-line/cd.md
        - Copy: command-line/cp.md
        - Exit: command-line/exit-command.md
        - Find: command-line/find-command.md
        - Help: command-line/help-command.md
        - History: command-line/history-command.md
        - Less: command-line/less-command.md
        - List: command-line/ls-command.md
        - Man: command-line/man-command.md
        - Mkdir: command-line/mkdir-command.md
        - Move: command-line/mv-command.md
        - Pwd: command-line/pwd-command.md
        - Remove: command-line/rm-command.md
        - Shell: command-line/the-shell.md
        - Touch: command-line/touch-command.md
        - What is: command-line/whatis-command.md
    - Text Maniplutaion:
        - Cut: text-manipulation/cut-command.md
        - Env: text-manipulation/env-command.md
        - Expand: text-manipulation/expand-command.md
        - Grep: text-manipulation/grep-command.md
        - Head: text-manipulation/head-command.md
        - Pipe/Tee: text-manipulation/pipe-tee-command.md
        - Sort: text-manipulation/sort-command.md
        - Tail: text-manipulation/tail-command.md
        - Translate (TR): text-manipulation/tr-translate-command.md
    - DNS:
        - What is DNS?: dns/what-is-dns.md
        - Components: dns/dns-components.md
        - Process: dns/dns-process.md
        - Setup: dns/dns-setup.md
        - Tools: dns/dns-tools.md
        - etc-hosts: dns/etc-hosts.md
    - Networking Fundamentals:
        - OSI Model: network-fundamentals/osi-model.md
        - TCP/IP Model: network-fundamentals/tcp-ip-model.md
        - Network Basics: network-fundamentals/network-basics.md
    - Routing:
        - What is a router: routing/what-is-a-router.md
        - Routing Protocols: routing/routing-protocols.md
        - Routing Table: routing/routing-table.md
        - Path of a packet: routing/path-of-a-packet.md
        - BGP Border Gateway Protocol: routing/bgp.md
    - Processes:
        - Process Details: processes/process-details.md
        - Process Creation: processes/process-creation.md
    - Filesystem:
        - Filesystem Hierarchy: filesystem/filesystem-hierarchy.md
        - Filesystem types: filesystem/filesystem-types.md
        - Creating filesytems: filesystem/creating-filesystems.md
        - Filesystem repair: filesystem/filesystem-repair.md
        - Inodes: filesystem/inodes.md
        - Symbolic Links: filesystem/symlinks.md
        - Swap Space: filesystem/swap-space.md
        - Mounting: filesystem/mounting.md
        - Disk Usage: filesystem/disk-usage.md
        - Disk partitioning: filesystem/disk-partitioning.md
        - Anatomy of a disk: filesystem/anatomy-of-a-disk.md
    - Kernel:
        - Overview: kernel/kernel-overview.md
        - Installation: kernel/kernel-installation.md
        - Modules: kernel/kernel-modules.md
        - Location: kernel/kernel-location.md
        - Privilege Levels: kernel/kernel-privilege-levels.md
        - System calls: kernel/system-calls.md
    - Network Troubleshooting:
        - Ping: network-troubleshooting/ping.md
        - Netstat: network-troubleshooting/netstat.md
        - Traceroute: network-troubleshooting/traceroute.md
        - ICMP: network-troubleshooting/icmp.md
        - Packet Analysis: network-troubleshooting/packet-analysis.md
    - User Management:
        - Users & Groups: user-management/users-and-groups.md
        - User Management Tools: user-management/user-management-tools.md
        - Root User: user-management/root-user.md
    - Linux Boot Process:
        - Overview: linux-process/boot-process-overview.md
        - (1) BIOS: linux-process/boot-process-bios.md
        - (2) Bootloader: linux-process/boot-process-bootloader.md
        - (3) Kernel: linux-process/boot-process-kernel.md
        - (4) Init: linux-process/boot-process-init.md
    - Subnetting:
        - Subnets: subnetting/subnets.m
        - IPv4: subnetting/ipv4.md
        - IPv6: subnetting/ipv6.md
        - NAT: subnetting/nat.md
        - CIDR: subnetting/cidr.md
    - Access:
        - File Permissions: access/file-permissions.md
        - Modifying Permissions: access/modifying-permissions.md
        - Ownership Permissions: access/ownership-permissions.md
        - Process Permissions: access/process-permissions.md
    - Devices:
        - Dev directory: devices/dev-directory.md
        - Device Types: devices/device-types.md
        - Device Names: devices/device-names.md
        - Listing Devices: devices/listing-devices.md
        - DD command: devices/dd.md
        - Sysfs: devices/sysfs.md
        - Udev: devices/udev.md
    - Process Utilisation:
        - Monitoring: process-utilization/continuous-monitoring.md
        - CPU Monitoring: process-utilization/cpu-monitoring.md
        - Cron Jobs: process-utilization/cron-jobs.md
        - I/O Monitoring: process-utilization/io-monitoring.md
        - Memory Monitoring: process-utilization/memory-monitoring.md
        - Process Threads: process-utilization/process-threads.md
        - Tracking Processes lsof: process-utilization/tracking-processes-lsof.md
        - Tracking Processes top: process-utilization/tracking-processes-top.md


- Contribute: CONTRIBUTING.md
- Code of Conduct: CODE_OF_CONDUCT.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  

copyright: |
  &copy; 2023 <a href="https://github.com/moabukar"  target="_blank" rel="noopener">Mohamed Abukar</a>

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/moabukar
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/moabukar_1
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/moabukar/
