site_name: Learn Linux
site_url: https://moabukar.github.io/unux-learn/
site_author: Mohamed Abukar
repo_url: https://github.com/moabukar/unix-learn
dev_addr: "127.0.0.1:8000"
docs_dir: docs
theme: 
  name: material
  # custom_dir: overrides
  extra_css:
    - stylesheets/custom.css

  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: dark_blue
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

nav:
- Home: home_page.md
- Linux:
    - Command-line:
        - Alias: command-line/alias-command.md
        - Cat: command-line/cat-command.md
        - Change Directory: command-line/cd.md
        - Copy: command-line/cp.md
        - Exit: command-line/exit-command.md
        - Find: command-line/find-command.md
        - Help: command-line/help-command.md
        - History: command-line/history-command.md
        - Less: command-line/less-command.md
    - DNS:
        - What is DNS?: dns/what-is-dns.md
        - DNS-Components: dns/dns-components.md
        - DNS-Process: dns/dns-process.md
        - DNS-Setup: dns/dns-setup.md
        - DNS-Tools: dns/dns-tools.md
        - etc-hosts: dns/etc-hosts.md
    - Networking Fundamentals:
        - OSI-Model: network-fundamentals/osi-model.md
        - TCP-IP: network-fundamentals/tcp-ip-model.md
        - Network Basics: network-fundamentals/network-basics.md
    - Routing:
        - What is a router: routing/what-is-a-router.md
        - Routing Protocols: routing/routing-protocols.md
        - Routing Table: routing/routing-table.md
        - Path of a packet: routing/path-of-a-packet.md
        - BGP Border Gateway Protocol: routing/bgp.md
    - Processes:
        - Process Details: processes/process-details.md
        - Process Creation: processes/process-creation.md
    - Filesystem:
        - Filesystem Hierarchy: filesystem/filesystem-hierarchy.md
        - Filesystem types: filesystem/filesystem-types.md
        - Creating filesytems: filesystem/creating-filesystems.md
        - Filesystem repair: filesystem/filesystem-repair.md
        - Inodes: filesystem/inodes.md
        - Symbolic Links: filesystem/symlinks.md
        - Swap Space: filesystem/swap-space.md
        - Mounting: filesystem/mounting.md
        - Disk Usage: filesystem/disk-usage.md
        - Disk partitioning: filesystem/disk-partitioning.md
        - Anatomy of a disk: filesystem/anatomy-of-a-disk.md
    - Kernel:
        - Kernel Overview: kernel/kernel-overview.md
        - Kernel Installation: kernel/kernel-installation.md
        - Kernel Modules: kernel/kernel-modules.md
        - Kernel Location: kernel/kernel-location.md
        - Kernel Privilege Levels: kernel/kernel-privilege-levels.md
        - System calls: kernel/system-calls.md
    - Network Troubleshooting:
        - Ping: network-troubleshooting/ping.md
        - Netstat: network-troubleshooting/netstat.md
        - Traceroute: network-troubleshooting/traceroute.md
        - ICMP: network-troubleshooting/icmp.md
        - Packet Analysis: network-troubleshooting/packet-analysis.md
    - User Management:
        - Users & Groups: user-management/users-and-groups.md
        - User Management Tools: user-management/user-management-tools.md
        - Root User: user-management/root-user.md
    - Linux Boot Process:
        - Boot Process Overview: linux-process/boot-process-overview.md
        - Boot Process BIOS: linux-process/boot-process-bios.md
        - Boot Process Bootloader: linux-process/boot-process-bootloader.md
        - Boot Process Kernel: linux-process/boot-process-kernel.md
        - Boot Process Init: linux-process/boot-process-init.md
    - Subnetting:
        - Subnets: subnetting/subnets.m
        - ipv4: subnetting/ipv4.md
        - ipv6: subnetting/ipv6.md
        - NAT: subnetting/nat.md
        - CIDR: subnetting/cidr.md



- Contribute: CONTRIBUTING.md
- Code of Conduct: CODE_OF_CONDUCT.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  

copyright: |
  &copy; 2023 <a href="https://github.com/moabukar"  target="_blank" rel="noopener">Mohamed Abukar</a>

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/moabukar
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/moabukar_1
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/moabukar/
