site_name: Learn Linux
site_url: https://moabukar.github.io/unux-learn/
site_author: Mohamed Abukar
repo_url: https://github.com/moabukar/unix-learn
dev_addr: "127.0.0.1:8000"
docs_dir: docs
theme: 
  name: material
  # custom_dir: overrides
  extra_css:
    - stylesheets/custom.css

  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: dark_blue
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

nav:
- Home: home_page.md
- Linux:
    - Command-line:
        - Alias: command-line/alias-command.md
        - Cat: command-line/cat-command.md
        - Change Directory: command-line/cd.md
        - Copy: command-line/cp.md
        - Exit: command-line/exit-command.md
        - Find: command-line/find-command.md
        - Help: command-line/help-command.md
        - History: command-line/history-command.md
        - Less: command-line/less-command.md
    - DNS:
        - What is DNS?: dns/what-is-dns.md
        - DNS-Components: dns/dns-components.md
        - DNS-Process: dns/dns-process.md
        - DNS-Setup: dns/dns-setup.md
        - DNS-Tools: dns/dns-tools.md
        - etc-hosts: dns/etc-hosts.md
    - Networking Fundamentals:
        - OSI-Model: network-fundamentals/osi-model.md
        - TCP-IP: network-fundamentals/tcp-ip-model.md
        - Network Basics: network-fundamentals/network-basics.md

- Contribute: CONTRIBUTING.md
- Code of Conduct: CODE_OF_CONDUCT.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  

copyright: |
  &copy; 2023 <a href="https://github.com/moabukar"  target="_blank" rel="noopener">Mohamed Abukar</a>

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/moabukar
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/moabukar_1
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/moabukar/
